apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  completions: 4
  parallelism: 2
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: busybox
          image: busybox
          command: ["sh", "-c", "echo Hello from Kubernetes Job && sleep 5"]
