apiVersion: v1
kind: Pod
metadata:
  name: pod-name
  namespace: pod-ns
  labels:
    app: pod-label
spec:
  restartPolicy: OnFailure
  volumes:
    - name: emptydir-storage
      emptydir: {}
  containers:
    - name: nginx-container
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: "250m"
          memory: "64Mi"
        limits:
          cpu: "250m"
          memory: "64Mi"
      volumeMounts:
        - name: emptydir-storage
          mountPaths: /logs
